   -- ====== Section 6 — Mixed / Challenge Tasks ======

   -- Task 36: For each state, find the total number of customers
-- AND the total revenue generated by those customers.

SELECT   c.state,
         COUNT(DISTINCT c.customer_id) AS total_customers,
         SUM(oi.quantity * p.list_price * (1 - oi.discount)) AS total_revenue
FROM     sales.customers AS c
         INNER JOIN
         sales.orders AS o
         ON c.customer_id = o.customer_id
         INNER JOIN
         sales.order_items AS oi
         ON o.order_id = oi.order_id
         INNER JOIN
         production.products AS p
         ON oi.product_id = p.product_id
GROUP BY c.state;

-- Task 37: Rank all products by price within each category.

SELECT
    p.product_name,
    p.list_price,
    c.category_name,
    RANK() OVER (
        PARTITION BY p.category_id
        ORDER BY p.list_price DESC
    ) AS price_rank
FROM production.products AS p
INNER JOIN production.categories AS c
    ON p.category_id = c.category_id;

    -- Task 38: Find the month-wise order count and total revenue for the year 2017.

SELECT
    MONTH(o.order_date) AS order_month,
    COUNT(DISTINCT o.order_id) AS order_count,
    SUM(oi.quantity * p.list_price * (1 - oi.discount)) AS total_revenue
FROM sales.orders AS o
INNER JOIN sales.order_items AS oi
    ON o.order_id = oi.order_id
INNER JOIN production.products AS p
    ON oi.product_id = p.product_id
WHERE YEAR(o.order_date) = 2017
GROUP BY MONTH(o.order_date)
ORDER BY order_month;

-- Task 39: List each store's best-selling product (by quantity sold).

SELECT store_name,
       product_name,
       total_quantity
FROM (
    SELECT
        st.store_name,
        p.product_name,
        SUM(oi.quantity) AS total_quantity,
        RANK() OVER (
            PARTITION BY st.store_id
            ORDER BY SUM(oi.quantity) DESC
        ) AS product_rank
    FROM sales.stores AS st
    INNER JOIN sales.orders AS o
        ON st.store_id = o.store_id
    INNER JOIN sales.order_items AS oi
        ON o.order_id = oi.order_id
    INNER JOIN production.products AS p
        ON oi.product_id = p.product_id
    GROUP BY st.store_id, st.store_name, p.product_id, p.product_name
) AS ranked_products
WHERE product_rank = 1;

-- Task 40: Store name, staff name, number of orders, and total revenue
-- grouped by store and staff member, sorted by revenue descending.

SELECT
    st.store_name,
    s.first_name + ' ' + s.last_name AS staff_name,
    COUNT(DISTINCT o.order_id) AS number_of_orders,
    SUM(oi.quantity * p.list_price * (1 - oi.discount)) AS total_revenue
FROM sales.stores AS st
INNER JOIN sales.staffs AS s
    ON st.store_id = s.store_id
INNER JOIN sales.orders AS o
    ON s.staff_id = o.staff_id
INNER JOIN sales.order_items AS oi
    ON o.order_id = oi.order_id
INNER JOIN production.products AS p
    ON oi.product_id = p.product_id
GROUP BY
    st.store_name,
    s.first_name,
    s.last_name
ORDER BY total_revenue DESC;